import mongoose from "mongoose";

const SalesStageSchema = new mongoose.Schema({
  label: {
    type: String,
    require: true,
  },
  description: {
    type: String,
  },
  level: {
    type: Number,
  },
});

const SalesStageModel = new mongoose.model("SalesStage", SalesStageSchema);
export default SalesStageModel;

// const data = [
//   {
//     _id: "670e85355a74d28e495aaf4e",
//     firstName: "ashwin",
//     lastName: "gorle",
//     entryDetails: {
//       currentQuarter: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 0,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 8,
//         prospectEntries: 5,
//         qualificationEntries: 50,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 6,
//         wonEntries: 2,
//       },
//       lastQuarter: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 0,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 1,
//         prospectEntries: 5,
//         qualificationEntries: 10,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 6,
//         wonEntries: 2,
//       },
//       last3rdQuarter: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 11,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 8,
//         prospectEntries: 5,
//         qualificationEntries: 50,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 25,
//         wonEntries: 2,
//       },
//       last4thQuarter: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 0,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 8,
//         prospectEntries: 5,
//         qualificationEntries: 50,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 6,
//         wonEntries: 2,
//       },
//       lastYear: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 0,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 8,
//         prospectEntries: 5,
//         qualificationEntries: 50,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 6,
//         wonEntries: 2,
//       },
//     },
//   },
//   {
//     _id: "670e85355a74d28e495aaf4e",
//     firstName: "ashwin",
//     lastName: "gorle",
//     entryDetails: {
//       currentQuarter: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 0,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 8,
//         prospectEntries: 5,
//         qualificationEntries: 50,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 6,
//         wonEntries: 2,
//       },
//       lastQuarter: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 0,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 1,
//         prospectEntries: 5,
//         qualificationEntries: 10,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 6,
//         wonEntries: 2,
//       },
//       last3rdQuarter: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 11,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 8,
//         prospectEntries: 5,
//         qualificationEntries: 50,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 25,
//         wonEntries: 2,
//       },
//       last4thQuarter: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 0,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 8,
//         prospectEntries: 5,
//         qualificationEntries: 50,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 6,
//         wonEntries: 2,
//       },
//       lastYear: {
//         clientEntries: 9,
//         contactEntries: 2,
//         registrationEntries: 0,
//         tenderEntries: 0,
//         mentionEntries: 6,
//         leadEntries: 8,
//         prospectEntries: 5,
//         qualificationEntries: 50,
//         followUpEntries: 2,
//         proposalEntries: 12,
//         closingEntries: 6,
//         wonEntries: 2,
//       },
//     },
//   },
// ];
